#!/usr/bin/env bash

### Omakub-macOS ######################################
# A script to set a system-wide look and feel for macOS
#######################################################

OMAKUB_PATH="$HOME/src/omakub-macos"

# We're gonna need brew
if ! command -v brew &>/dev/null; then
	echo "Installing homebrew..."
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# Some apps we need
# gum for choosing themes
# nvr for setting neovim colorscheme across all instances
for app in gum nvr; do
	if ! command -v $app &>/dev/null; then
		echo "Installing $app..."
		brew install $app
	fi
done

# Pick a preconfigured theme
THEME_NAMES=("Onedark" "Everforest" "Gruvbox" "Kanagawa" "Rose Pine Dawn")
THEME=$(gum choose "${THEME_NAMES[@]}" --header "Choose your theme" --height 9 | tr '[:upper:]' '[:lower:]' | sed 's/ /-/g')
[ -z "$THEME" ] && echo "No theme selected" && exit 0

# Translate to specific vars
if [ "$THEME" == "gruvbox" ]; then
	DARK_MODE="true"
	ITERM_THEME="gruvbox-dark"
	WALLPAPER="$OMAKUB_PATH/backgrounds/fog_forest_2.jpg"
	NVIM_BACKGROUND="dark"
elif [ "$THEME" == "onedark" ]; then
	DARK_MODE="true"
	ITERM_THEME="onedark"
	WALLPAPER="$OMAKUB_PATH/backgrounds/80s-retro-tropical-sunset-by-freepik.jpg"
	NVIM_BACKGROUND="dark"
elif [ "$THEME" == "everforest" ]; then
	DARK_MODE="true"
	ITERM_THEME="everforest_dark_low"
	WALLPAPER="$OMAKUB_PATH/backgrounds/ferns-green.jpg"
	NVIM_BACKGROUND="dark"
elif [ "$THEME" == "kanagawa" ]; then
	DARK_MODE="true"
	ITERM_THEME="kanagawa_dragon"
	WALLPAPER="$OMAKUB_PATH/backgrounds/kanagawa.jpg"
	NVIM_BACKGROUND="dark"
elif [ "$THEME" == "rose-pine-dawn" ]; then
	DARK_MODE="false"
	ITERM_THEME="rose-pine-dawn"
	WALLPAPER="$OMAKUB_PATH/backgrounds/simple-pastel-by-triarts-from-freepik.jpg"
	NVIM_BACKGROUND="light"
fi

# set iterm profile
if [[ $TERM_PROGRAM == "iTerm.app" ]] || [[ -n $ITERM_SESSION_ID ]]; then
	osascript -e "
  tell application \"iTerm\"
    tell every window
      tell every tab
        tell every session
          set color preset to \"$ITERM_THEME\"
        end tell
      end tell
    end tell
  end tell"
fi

# set dark mode
if [ "$DARK_MODE" = "true" ]; then
	osascript -e 'tell application "System Events" to tell appearance preferences to set dark mode to true'
else
	osascript -e 'tell application "System Events" to tell appearance preferences to set dark mode to false'
fi

# set wallpaper
osascript -e "tell application \"Finder\"
  set desktop picture to POSIX file \"$WALLPAPER\"
end tell"

# set alacritty theme if it's installed
if command -v alacritty &>/dev/null; then
	cp "$OMAKUB_PATH/themes/alacritty/$THEME.toml" ~/.config/alacritty/theme.toml
	touch ~/.config/alacritty/alacritty.toml
fi

# set neovim theme
cp "$OMAKUB_PATH/themes/neovim/$THEME.lua" ~/.config/nvim/lua/plugins/theme.lua
for servername in $(nvr --serverlist); do
	nvr --servername "$servername" --remote-send ":colorscheme $THEME | set background=$NVIM_BACKGROUND<CR>"
done

exit 0
